# Generated by Django 4.0.4 on 2022-04-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='N/A', max_length=250),
        ),
    ]
