# Generated by Django 4.0.4 on 2022-04-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_car_car_model_car_color_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default=0),
        ),
    ]
