# Generated by Django 4.0.4 on 2022-04-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_oilchange_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='lastOilChange',
            field=models.IntegerField(default=0),
        ),
    ]
